// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjozPPO0j8Ph2wZBu_KVCU9QAKT8r_0tM',
    appId: '1:593479066939:web:a2a7447116a7f45652031e',
    messagingSenderId: '593479066939',
    projectId: 'bcag-a6ac7',
    authDomain: 'bcag-a6ac7.firebaseapp.com',
    storageBucket: 'bcag-a6ac7.appspot.com',
    measurementId: 'G-EG67ZNBJ4C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACuu6hH4Xd195AHOPMIEfhjJMpc_PrZPc',
    appId: '1:593479066939:android:5afdb6bd698fb21c52031e',
    messagingSenderId: '593479066939',
    projectId: 'bcag-a6ac7',
    storageBucket: 'bcag-a6ac7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4RBZQWxrF4IRWak77H-bniWabzEwfJng',
    appId: '1:593479066939:ios:24c90bc52d81a07d52031e',
    messagingSenderId: '593479066939',
    projectId: 'bcag-a6ac7',
    storageBucket: 'bcag-a6ac7.appspot.com',
    iosBundleId: 'com.example.churchManagementAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4RBZQWxrF4IRWak77H-bniWabzEwfJng',
    appId: '1:593479066939:ios:86ed39472405150f52031e',
    messagingSenderId: '593479066939',
    projectId: 'bcag-a6ac7',
    storageBucket: 'bcag-a6ac7.appspot.com',
    iosBundleId: 'com.example.churchManagementAdmin.RunnerTests',
  );
}
